# Generated by Django 5.2.17 on 2026-09-22 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_alter_musics_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musics',
            name='category',
            field=models.CharField(choices=[('keren', 'Keren'), ('lawas', 'Lawas'), ('semangat', 'Semangat'), ('nasional', 'Nasional')], default='keren', max_length=20),
        ),
    ]
