# Generated by Django 5.2.17 on 2026-09-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_starred_by_alter_musics_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='category',
            field=models.CharField(choices=[('nasional', 'Nasional'), ('keren', 'Keren'), ('semangat', 'Semangat'), ('lawas', 'Lawas')], default='keren', max_length=20),
        ),
    ]
